spring:
  application:
    name: product-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
